baseURL = 'https://advokatpougolovnymdelam.com/'
languageCode = 'en-us'
title = '–ê–¥–≤–æ–∫–∞—Ç –ø–æ —É–≥–æ–ª–æ–≤–Ω—ã–º –¥–µ–ª–∞–º Portugal'
theme = "archie"
copyright = "¬© advokatpougolovnymdelam.com"

[pagination]
pagerSize = 10

[markup]
[markup.highlight]
noClasses = false
style = "monokai"
codeFences = true
guessSyntax = true

[frontmatter]
date = [':filename', ':default']
section = ['categories']

[permalinks]
posts = '/:section/:slugorcontentbasename/'

[params]
mode = "auto"
useCDN = false
subtitle = " ‚öñÔ∏è Portuguese criminal defense lawyer  üáµüáπ "

[[params.social]]
name = "Bluesky"
icon = "cloud"
url = "https://bsky.app/"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/advokatpougolovnymdelam"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://www.linkedin.com/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[module]
[[module.mounts]]
source = "assets"
target = "static/assets"
